name = "idkaboutbytes/rxbrioutils"
version = "1.0.1"
description = "RxBrioUtils package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/rxbrioutils"
includes = ["pesde.toml", "README.md", "CHANGELOG.md", "default.project.json", "src/**/*.luau"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Observable = { repo = "idkaboutbytes/observable", rev = "v1.0.0" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.2" }
Brio = { repo = "idkaboutbytes/brio", rev = "v1.2.1" }
Maid = { repo = "idkaboutbytes/maid", rev = "v1.1.1" }
Rx = { repo = "idkaboutbytes/rx", rev = "v1.0.4" }
